//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToUs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableManager
    {
        public string TableName { get; set; }
        public int ClassManagerId { get; set; }
        public string PicturePath { get; set; }
    
        public virtual ClassManager ClassManager { get; set; }
        public virtual TimeTable TimeTable { get; set; }
    }
}
